micronaut:
  application:
    name: pixKeymanagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  #default:
    #url: jdbc:postgresql://localhost:5432/pixdb
    #driverClassName: org.postgresql.Driver
    #username: postgres
    #password: postgres
    #schema-generate: CREATE_DROP
    #dialect: POSTGRES

  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/pixdb`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    dialect: org.hibernate.dialect.MySQL8Dialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'

bcb:
  pix:
    url: 'http://localhost:8082'